apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lukscryptwalker-csi.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lukscryptwalker-csi.controller.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "lukscryptwalker-csi.fullname" . }}-controller
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "lukscryptwalker-csi.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lukscryptwalker-csi.controller.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "lukscryptwalker-csi.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "lukscryptwalker-csi.controller.serviceAccountName" . }}
      {{- with .Values.podSecurityContext.controller }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: csi-provisioner
        image: {{ .Values.controller.sidecars.provisioner.image.repository }}:{{ .Values.controller.sidecars.provisioner.image.tag }}
        imagePullPolicy: {{ .Values.controller.sidecars.provisioner.image.pullPolicy }}
        args:
        - "--csi-address=$(ADDRESS)"
        - "--v={{ .Values.logging.level }}"
        - "--feature-gates=Topology=true"
        - "--strict-topology=false"
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy/
      - name: csi-resizer
        image: {{ .Values.controller.sidecars.resizer.image.repository }}:{{ .Values.controller.sidecars.resizer.image.tag }}
        imagePullPolicy: {{ .Values.controller.sidecars.resizer.image.pullPolicy }}
        args:
        - "--csi-address=$(ADDRESS)"
        - "--v={{ .Values.logging.level }}"
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy/
      - name: lukscryptwalker-csi
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--nodeid=$(KUBE_NODE_NAME)"
        - "--vfs-cache-size={{ .Values.node.vfsCacheSize }}"
        env:
        - name: CSI_ENDPOINT
          value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_LOCAL_PATH
          value: {{ .Values.storage.defaultPath | quote }}
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: local-path
          mountPath: {{ .Values.storage.defaultPath }}
        {{- with .Values.securityContext.controller }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.controller.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: socket-dir
        emptyDir: {}
      - name: local-path
        hostPath:
          path: {{ .Values.storage.defaultPath }}
          type: DirectoryOrCreate
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}