apiVersion: v2
name: lukscryptwalker-csi
description: A Helm chart for LUKSCryptWalker - LUKS CSI Driver - Kubernetes CSI driver with LUKS encryption
type: application
version: 1.2.11
appVersion: "1.2.11"
keywords:
  - storage
  - csi
  - luks
  - encryption
home: https://github.com/Algonomia/lukscryptwalker-csi
sources:
  - https://github.com/Algonomia/lukscryptwalker-csi
maintainers:
  - name: Brice GUILLAUME - Algonomia
    email: brice.guillaume@algonomia.com
annotations:
  category: Storage
